"""Add owner_id to jobs

Revision ID: 1c6bcfeb7860
Revises: 8a5d31605f8d
Create Date: 2025-02-16 16:20:42.990359

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1c6bcfeb7860'
down_revision: Union[str, None] = '8a5d31605f8d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('jobs', sa.Column('owner_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'jobs', 'users', ['owner_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'jobs', type_='foreignkey')
    op.drop_column('jobs', 'owner_id')
    # ### end Alembic commands ###
