"""Add resume_url to applications

Revision ID: 2653b53ea392
Revises: 7edbe2bf18df
Create Date: 2025-04-03 14:41:48.759954

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '2653b53ea392'
down_revision: Union[str, None] = '7edbe2bf18df'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('applications', sa.Column('resume_url', sa.String(), nullable=True))
    op.alter_column('applications', 'responses',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('applications', 'responses',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               nullable=True)
    op.drop_column('applications', 'resume_url')
    # ### end Alembic commands ###
