"""Add job_posted_date and application_deadline to jobs

Revision ID: 2b20b7aa8dfb
Revises: f88b08103986
Create Date: 2025-03-24 13:15:44.439066

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2b20b7aa8dfb'
down_revision: Union[str, None] = 'f88b08103986'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('jobs', sa.Column('job_posted', sa.String(), nullable=True))
    op.add_column('jobs', sa.Column('job_expiration', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('jobs', 'job_expiration')
    op.drop_column('jobs', 'job_posted')
    # ### end Alembic commands ###
