"""Add job_questions and url_descriptions to jobs

Revision ID: 6633fe35aa9c
Revises: c6b75ca5e631
Create Date: 2025-04-04 15:04:49.792223

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6633fe35aa9c'
down_revision: Union[str, None] = 'c6b75ca5e631'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('jobs', sa.Column('other_materials', sa.JSON(), nullable=True))
    op.add_column('jobs', sa.Column('job_questions', sa.JSON(), nullable=True))
    op.add_column('jobs', sa.Column('url_descriptions', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('jobs', 'url_descriptions')
    op.drop_column('jobs', 'job_questions')
    op.drop_column('jobs', 'other_materials')
    # ### end Alembic commands ###
