"""Add location column to jobs

Revision ID: 6a7296ecd7b4
Revises: fc457d1de9bc
Create Date: 2025-03-18 17:48:27.449382

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '6a7296ecd7b4'
down_revision: Union[str, None] = 'fc457d1de9bc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('jobs', sa.Column('in_person_mode', sa.String(), nullable=True))
    op.add_column('jobs', sa.Column('compensation', sa.String(), nullable=True))
    op.add_column('jobs', sa.Column('location', sa.String(), nullable=True))
    op.drop_index('idx_jobs_title', table_name='jobs')
    op.create_index('idx_jobs_title', 'jobs', ['title'], unique=False)
    op.drop_column('users', 'role')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('role', postgresql.ENUM('admin', 'recruiter', 'applicant', name='userrole'), server_default=sa.text("'applicant'::userrole"), autoincrement=False, nullable=False))
    op.drop_index('idx_jobs_title', table_name='jobs')
    op.create_index('idx_jobs_title', 'jobs', [sa.text('lower(title::text)')], unique=False)
    op.drop_column('jobs', 'location')
    op.drop_column('jobs', 'compensation')
    op.drop_column('jobs', 'in_person_mode')
    # ### end Alembic commands ###
