"""Add responses column to Application

Revision ID: 8b6b82081aac
Revises: bedcee046aa0
Create Date: 2025-04-03 10:44:54.122062

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '8b6b82081aac'
down_revision: Union[str, None] = 'bedcee046aa0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_applications_id', table_name='applications')
    op.drop_table('applications')
    op.create_index('idx_jobs_title', 'jobs', ['title'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_jobs_title', table_name='jobs')
    op.create_table('applications',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('job_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('status', postgresql.ENUM('accepted', 'rejected', 'not_reviewed', name='applicationstatus'), server_default=sa.text("'not_reviewed'::applicationstatus"), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['job_id'], ['jobs.id'], name='applications_job_id_fkey'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='applications_user_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='applications_pkey')
    )
    op.create_index('ix_applications_id', 'applications', ['id'], unique=False)
    # ### end Alembic commands ###
