"""Remove company from jobs

Revision ID: c015a1ccacb9
Revises: 2b20b7aa8dfb
Create Date: 2025-03-24 15:30:42.273447

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c015a1ccacb9'
down_revision: Union[str, None] = '2b20b7aa8dfb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
