"""Add created_at to applications

Revision ID: c6b75ca5e631
Revises: 68758dbdbc09
Create Date: 2025-04-04 13:51:30.345991

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c6b75ca5e631'
down_revision: Union[str, None] = '68758dbdbc09'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('applications', sa.Column('created_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('applications', 'created_at')
    # ### end Alembic commands ###
