"""Remove company field from Job model

Revision ID: db368e27fc19
Revises: 89dca961330c
Create Date: 2025-03-24 15:40:51.268717

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'db368e27fc19'
down_revision: Union[str, None] = '89dca961330c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('jobs', 'company')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('jobs', sa.Column('company', sa.VARCHAR(), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
