"""Added full CRUD for Job

Revision ID: f49b7497c1b4
Revises: da07aa44f16c
Create Date: 2025-02-14 11:51:21.096870

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f49b7497c1b4'
down_revision: Union[str, None] = 'da07aa44f16c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('jobs', 'title',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('jobs', 'description',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('jobs', 'company',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.drop_index('ix_jobs_title', table_name='jobs')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_jobs_title', 'jobs', ['title'], unique=False)
    op.alter_column('jobs', 'company',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('jobs', 'description',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('jobs', 'title',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###
